### ISSUE TITLE
Imported Svelte elements show as being unused even if used in the body of the svelte file.

### ISSUE THREAD

**Issue by JoshuaJWilborn** [coc-extensions/coc-svelte#1]

**Comment by iamcco** [comment]
Should be issue of upstream. https://github.com/UnwrittenFun/svelte-vscode/issues/79

Using `"svelte.plugin.typescript.diagnostics.enable": false` to suppress by now.

**Comment by AnatoleLucet** [comment]
Any update on that?

**Comment by monkoose** [comment]
Same question.
Is it at least possible to disable specific errors with coc preferences? Which linter this `svelte.plugin.typescript.diagnostics.enable` use? Maybe it can be done with the linter configuration.
