### ISSUE TITLE
Mention in the README that a syntax highlighting plugin is necessary

### ISSUE THREAD

**Issue by fnune** [coc-extensions/coc-svelte#10]
The README indicates that this extension provides syntax highlighting. However, for it to work, it needs to be installed in tandem with a syntax highlighting plugin (I used `leafOfTree/vim-svelte-plugin`).

Does this need to be mentioned in the README?

**Comment by iamcco** [comment]
I had updated the README for that.

**Comment by fnune** [comment]
Awesome! Thank you, this will save time for noobies like me coming to the README :)
