### ISSUE TITLE
Go to definition with @rollup/plugin-alias

### ISSUE THREAD

**Issue by icalvin102** [coc-extensions/coc-svelte#14]
Is there a way to get 'go to definition' working with [@rollup/plugin-alias](https://www.npmjs.com/package/@rollup/plugin-alias)?

Go to difinition works as expected with relative paths but as soon as I change the import to use an alias I get:
`[coc.nvim]: Error on notification "jumpDefinition": Cannot read property 'start' of undefined`

As my Project grows the relative import paths are getting quite messy. Thats the reason way would like to use [@rollup/plugin-alias](https://www.npmjs.com/package/@rollup/plugin-alias). Or is there another way to use abolute paths that works well with 'go to definition'?

Thanks for providing coc-svelte :)

**Comment by davidroeca** [comment]
:thinking: this one's tough -- sorry for the late reply. One thing you could try is set up a `tsconfig.json` and use the typescript language server to achieve this. Though unfortunately you'd have to translate your alias config to TS.

Relevant options include:
- [baseUrl](https://www.typescriptlang.org/tsconfig#baseUrl)
- [paths](https://www.typescriptlang.org/tsconfig#paths)

Potentially some others, too

**Comment by icalvin102** [comment]
@davidroeca thanks. `baseUrl` and `paths` in tsconfig.json solved it.

**Comment by peterbabic** [comment]
> @davidroeca thanks. `baseUrl` and `paths` in tsconfig.json solved it.

Can you please show how did you do that?

**Comment by peterbabic** [comment]
> thanks. `baseUrl` and `paths` in tsconfig.json solved it.

@icalvin102 can you please show how did you do that?

**Comment by icalvin102** [comment]
@peterbabic this are the things I added to my config:

tsconfig.json
```diff
    "compilerOptions": {
        "lib": ["ES2019", "ES2017", "ES5", "ES6", "DOM"],
+       "baseUrl": ".",
+       "paths": {
+         "$src/*": ["src/*"],
+         "$lib/*": ["src/components/*"]
+      }
    },

```

rollup.config.js
```diff
+import alias from '@rollup/plugin-alias';
export default [
  {
    input: 'src/main.ts',
    output: {
      sourcemap: true,
      format: 'iife',
      name: 'app',
      file: 'public/build/bundle.js',
    },
    plugins: [
      ...otherPlugins,
+     alias({
+       resolve: ['.js', '.ts', '.svelte'],
+       entries: [
+         { find: '$src', replacement: './src' },
+         { find: '$lib', replacement: './src/components' },
+       ]
+     })
    ],
  },
]
```

It works in typescript and svelte files. However in svelte files autocompletion only works if the closing `'` or `"` is present. 

Example: `import Foo from '$lib/<cursor>` will not autocomplete correctly but `import Foo from '$lib/<cursor>'` will.
