### ISSUE TITLE
[coc.nvim] The "svelte" server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by dvlpr91** [coc-extensions/coc-svelte#15]
Hi.

After installation, features such as auto-completion do not work.

**Comment by geigerzaehler** [comment]
The output shows “Error: Cannot find module 'typescript'”. `npm install typescript` from `~/.config/coc/extensions/node_modules/coc-svelte` fixed the issue.

**Comment by dvlpr91** [comment]
> The output shows “Error: Cannot find module 'typescript'”. `npm install typescript` from `~/.config/coc/extensions/node_modules/coc-svelte` fixed the issue.


So it works

Hope it will be fixed soon.

Thanks!

**Comment by geigerzaehler** [comment]
Maybe it makes sense to keep this open as it is not actually fixed in the code?

**Comment by pappasam** [comment]
Yes, this is still very much an issue. To get around it for now, build this coc extension using a Vim package/plugin manager instead of installing it with `CocInstall`. If using [vim-packager](https://github.com/kristijanhusak/vim-packager):

```vim
call packager#add('git@github.com:coc-extensions/coc-svelte.git', {'do': 'yarn install --frozen-lockfile && yarn build'})
```

The above works because `typescript` is a devDependency, which only gets installed if you build this project from source. Installing it from npm doesn't install the development dependencies.

**Comment by MaMrEzO** [comment]
> Yes, this is still very much an issue. To get around it for now, build this coc extension using a Vim package/plugin manager instead of installing it with `CocInstall`. If using [vim-packager](https://github.com/kristijanhusak/vim-packager):
> 
> ```viml
> call packager#add('git@github.com:coc-extensions/coc-svelte.git', {'do': 'yarn install --frozen-lockfile && yarn build'})
> ```
> 
> The above works because `typescript` is a devDependency, which only gets installed if you build this project from source. Installing it from npm doesn't install the development dependencies.

Nothing different with `:CocInstall` but more ram utilization(?) and failed to load too....

In compare to the VSCode version its take too long to load the project(and then fail...)
I love the (Neo)Vim a lot, take care of it plz...

**Comment by MaMrEzO** [comment]
> > Yes, this is still very much an issue. To get around it for now, build this coc extension using a Vim package/plugin manager instead of installing it with `CocInstall`. If using [vim-packager](https://github.com/kristijanhusak/vim-packager):
> > ```viml
> > call packager#add('git@github.com:coc-extensions/coc-svelte.git', {'do': 'yarn install --frozen-lockfile && yarn build'})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The above works because `typescript` is a devDependency, which only gets installed if you build this project from source. Installing it from npm doesn't install the development dependencies.
> 
> Nothing different with `:CocInstall` but more ram utilization(?) and failed to load too....
> 
> In compare to the VSCode version its take too long to load the project(and then fail...)
> I love the (Neo)Vim a lot, take care of it plz...

**TAKE CARE OF YOUR `tsconfig` OF YOU PROJECT THIS MIGHT BE THE LITTLE EVIL**
