### ISSUE TITLE
Prettier doesn't work in .svelte files

### ISSUE THREAD

**Issue by Alci6** [coc-extensions/coc-svelte#19]
How can I active Prettier when I save in .svelte with this extension? 

Thans for your work!

**Comment by davidroeca** [comment]
You'll need to configure prettier to run with [prettier-plugin-svelte](https://github.com/sveltejs/prettier-plugin-svelte). This extension does not format on save, the docs should probably be updated. You can try setting up another vim formatter for now like [vim-filetype-formatter](https://github.com/pappasam/vim-filetype-formatter) or [neoformat](https://github.com/sbdchd/neoformat)  to handle this for now.

**Comment by davidroeca** [comment]
@Alci6 closing -- comment here if you're still having trouble, or open another issue if you think it's related to a bug
