### ISSUE TITLE
Does not work if installed using Vim package manager

### ISSUE THREAD

**Issue by pappasam** [coc-extensions/coc-svelte#2]
Coc now supports installing extensions using Vim package managers. See: https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension . This extension does not work for me when installed with my package manager. For example, with vim-packager:

```vim
  call packager#add('git@github.com:coc-extensions/coc-svelte.git', {
        \ 'do': 'yarn install',
        \ })
```

This technique works for every other extension I've used so far . I also confirm that coc-svelte works for me when installed using CocInstall coc-svelte.

My environment:

```
## versions

vim version: NVIM v0.5.0-dev
node version: v12.9.1
coc.nvim version: 0.0.74-6700e7468d
term: xterm-256color
platform: linux

## Messages

## Output channel: snippets
```

**Comment by iamcco** [comment]
Use `yarn install && yarn build` instead

**Comment by pappasam** [comment]
@iamcco ok, it now works (albeit with build errors). Thanks for the tip!
