### ISSUE TITLE
Extension out of date

### ISSUE THREAD

**Issue by abalmos** [coc-extensions/coc-svelte#24]
Are their plans to sync this extension back with the vscode-svelte extension? 

It appears the implementation is now old enough that parts are broken. For example: https://github.com/sveltejs/language-tools/issues/932

I tried my hand at the upgrade, but quickly realized I do not know enough about `coc.nvim`. It appears to not provide many of the exports that `vscode` does.

**Comment by timjackleus** [comment]
I've been having problems with this as well, for the time being it can be solved by installing the plugin separately.
```
Plug 'codechips/coc-svelte', {'do': 'npm install'}
```
Source: https://codechips.me/vim-setup-for-svelte-development/

**Comment by davidroeca** [comment]
Apologies for this! I was hoping to use svelte in my next project but ended up using react in the end so haven’t had much time to devote to svelte. If upgrading the package  solves most of your problems, feel free to submit a PR. 

I’m unclear whether any of the latest changes may require updates to the vim plugin itself, which may be more involved.
