### ISSUE TITLE
Cannot find module './html/autoClose'

### ISSUE THREAD

**Issue by jesperp** [coc-extensions/coc-svelte#28]
I am getting this error when installing from scratch. First coc.vim via Plug and then simply `:CocInstall coc-svelte`. When opening svelte files I see this in my :CocInfo log

```
ERROR (pid:6017) [extensions] - Error on createExtension coc-svelte from
/Users/johndoe/.config/coc/extensions/node_modules/coc-svelte/lib/src/extension.js Error:
Cannot find module './html/autoClose'
```

Looking into the coc-svelte/lib/src directory I can only see extension.js, no other files...

Any ideas?

nvim 0.4.4
coc.nvim version: 0.0.80-2cece2600a
coc-svelte 0.2.3
macOS 11.2.3

**Comment by davidroeca** [comment]
Should have been fixed. Try a `:CocUpdate`
