### ISSUE TITLE
Consider Official Svelte Language Server

### ISSUE THREAD

**Issue by justinmoon** [coc-extensions/coc-svelte#4]
Svelte recently created an [official language server](https://github.com/sveltejs/language-tools#packages) that's still in "beta".

Perhaps this plugin should consider adopting at some point?

**Comment by peterbabic** [comment]
What is required for this to become reality? What advantages would it provide? 

DISCLAIMER: I am nvim and CoC user, I am pro this feature, just want to understand it more.

**Comment by Jayphen** [comment]
Here’s a document outlining the features of the official language tools, which are under active development: https://github.com/sveltejs/language-tools/issues/83

I am not sure exactly what the differences are, but it has many months of active development since forking from the codebase that coc-svelte is depending on.

**Comment by davidroeca** [comment]
I currently have a fork [here](https://github.com/davidroeca/coc-svelte) that targets [the new svelte-vscode](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode).

Just opened a PR for this https://github.com/coc-extensions/coc-svelte/pull/8

Feel free to comment on that PR if you have any issues using it; I'll try continually push those updates to the master branch in my fork until this PR gets merged or we have another solution in place.

**Comment by Jayphen** [comment]
@davidroeca Thank you for your effort.

What is the process for installing the version in your fork?

**Comment by davidroeca** [comment]
Sorry replied to the wrong thread https://github.com/coc-extensions/coc-svelte/pull/8#issuecomment-646604551

**Comment by Jayphen** [comment]
Thanks, that seems to work.

Do you know what is causing these linting errors? Is this to be expected with the coc-svelte, or have I configured something incorrectly?

![CleanShot 2020-06-19 at 17 52 39](https://user-images.githubusercontent.com/329184/85152815-bcef8700-b255-11ea-945d-92235a83b377.png)
