### ISSUE TITLE
Error on activate extension coc-svelte

### ISSUE THREAD

**Issue by pedrokpp** [coc-extensions/coc-svelte#49]
Hey, I've been using for a while this extension and I've enjoyed it a lot, it helps with a lot of stuff but today I've tried using it and couldn't because of some error I'm not sure why is happening...

I've tried searching for the possible source of it but couldn't find anything... any ideas on how to fix this?

Steps to reproduce:
1. Open a file that ends in `.svelte`
![image](https://user-images.githubusercontent.com/77463574/160730061-916dc353-114d-41d2-b550-94c25baa975b.png)

```bash
[~]$ uname -a
Linux archlinux 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux
[~]$ npm --version              
8.5.5
[~]$ node --version
v17.8.0
[~]$ nvim --version             
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
![image](https://user-images.githubusercontent.com/77463574/160730277-af67f1a2-1848-48a9-a5d0-a1c648dc349d.png)

**Comment by dak-384** [comment]
I have this issue as well when trying to activate the extension.

**Comment by pedrokpp** [comment]
seems to be working now, not sure if they did something

ty!

**Comment by LeoEricson** [comment]
I am also experiencing this issue.
