### ISSUE TITLE
Weird bug with emmet and CocAction('format')

### ISSUE THREAD

**Issue by monkoose** [coc-extensions/coc-svelte#6]
I have this weird behavior that is shown on this gif
![](https://i.imgur.com/GNmWIxu.gif)

As you can see when i select emmet autocompletion item for some reason it `removes` previously typed word and then i hit autocomplete key to expand it. But when format called by saving buffer or just calling CocAction('format') it on each invocation adds this removed part of the word.

I don't have this behavior with normal emmet in html files - it actually properly selects autocompletion item without removing part of a typed word and do not add anything with format.

Only me?

**Comment by iamcco** [comment]
Can not reproduce.

**Comment by monkoose** [comment]
Hm. 
How selecting emmet abbreviation works for you? Does previously typed part of the word dissapear?
Any idea where to dig?

**Comment by monkoose** [comment]
@iamcco 
> Can not reproduce.

Can you try this.
- Type `scri`
- Select `script` abbreviation with `C-n`
- Expand abbreviation with `Tab`
- Exit insert mode and type `:call coc#refresh()`
- Then `:call CocAction('format')` few times

**Comment by iamcco** [comment]
OK, I have reproduce this issue. It seems coc's issue.

**Comment by iamcco** [comment]
https://github.com/neoclide/coc.nvim/issues/1899

**Comment by monkoose** [comment]
> [neoclide/coc.nvim#1899](https://github.com/neoclide/coc.nvim/issues/1899)

Thank You. Let's wait for response.

**Comment by monkoose** [comment]
Seems like neoclide/coc.nvim@9389cc5e30fc55f5fea5e7bb1bb79e71c6c03338 fixes placement of removed part of the word on format. Still weird behavior with removed part of the word on selecting it in the pum popup.
