### ISSUE TITLE
Extension seems not to be running at all

### ISSUE THREAD

**Issue by fnune** [coc-extensions/coc-svelte#9]
Hello, thanks for this extension!

I'm sorry I have to post such a vague issue, but I can't seem to make the extension work at all. I have no syntax highlighting on `.svelte` files and none of the features advertised in the documentation.

![image](https://user-images.githubusercontent.com/16181067/86495273-f4dbeb80-bd78-11ea-8f38-238dcb19983d.png)

I've installed the extension using `:CocInstall coc-svelte`. I have also tried installing `svelte-language-server` globally and pointing Coc to the executable (successfully) with `"svelte.language-server.runtime": "/home/fausto/.volta/bin/svelteserver"`. But I still can't get it to work.

There seem to be two things that may influence this:

- If I run `set filetype?` on my `App.svelte` file I get `filetype=` (empty). However, if I set it with `set filetype=svelte`, it doesn't work either.
- If I don't run `svelte.restartLanguageServer`, the server apparently doesn't start at all (going by the logs, there's no mention of the extension there). However, even after I run `svelte.restartLanguageServer`, the server restarts successfully but the extension has no effect.

Results of `CocOpenLog` after opening `App.svelte`:

```
2020-07-03T21:58:57.897 INFO (pid:20017) [services] - registered service "eslint"
2020-07-03T21:58:58.124 INFO (pid:20017) [plugin] - coc.nvim 0.0.78-c9246e45a1 initialized with node: v12.18.1 after 306ms
```

Results of `CocOpenLog` after additionally running `svelte.restartLanguageServer`:

```
2020-07-03T22:01:31.038 INFO (pid:20665) [services] - registered service "eslint"
2020-07-03T22:01:31.259 INFO (pid:20665) [plugin] - coc.nvim 0.0.78-c9246e45a1 initialized with node: v12.18.2 after 295ms
2020-07-03T22:02:02.569 INFO (pid:20665) [language-client-index] - svelte started with 20763
2020-07-03T22:02:03.071 INFO (pid:20665) [language-client-index] - svelte started with 20772
```

Suspiciously there are two entries for svelte now.

Any idea what could be happening?

**Comment by iamcco** [comment]
Install s svelte syntax highlight plugin.

**Comment by fnune** [comment]
It works after installing a syntax highlight plugin. I used `leafOfTree/vim-svelte-plugin`.

**Comment by fnune** [comment]
https://github.com/coc-extensions/coc-svelte/issues/10

Thanks for the help!
